/* auto-generated, do not edit */
#include "star_rod_macros.h"

// type: MapProperties
#define GEN_MAP_LOCATION LOCATION_TOAD_TOWN_TUNNELS

// type: EntryList
#define GEN_ENTRY_LIST \
    {  330.0,   20.0,    0.0,  270.0 },

// type: TexPanner
#define GEN_TEX_PANNER_1 \
    TEX_PAN_PARAMS_ID(TEX_PANNER_1) \
    TEX_PAN_PARAMS_STEP(    50,   200,   110,   500) \
    TEX_PAN_PARAMS_FREQ(     1,     1,     1,     1) \
    TEX_PAN_PARAMS_INIT(     0,     0,     0,     0)

// type: Marker:Entry
// name: Entry_0
#define GEN_ENTRY_0_X 330
#define GEN_ENTRY_0_Y 20
#define GEN_ENTRY_0_Z 0
#define GEN_ENTRY_0_DIR 270
#define GEN_ENTRY_0_VEC 330,20,0

// type: Marker:Entity:HiddenYellowBlock
// name: HiddenYellowBlock_1
#define GEN_HIDDEN_YELLOW_BLOCK_1_X -52
#define GEN_HIDDEN_YELLOW_BLOCK_1_Y 70
#define GEN_HIDDEN_YELLOW_BLOCK_1_Z -32
#define GEN_HIDDEN_YELLOW_BLOCK_1_DIR 0
#define GEN_HIDDEN_YELLOW_BLOCK_1_VEC -52,70,-32
#define GEN_HIDDEN_YELLOW_BLOCK_1_XYZA -52, 70, -32, 0
#define GEN_HIDDEN_YELLOW_BLOCK_1_ITEM ITEM_COIN
#define GEN_HIDDEN_YELLOW_BLOCK_1_PARAMS GEN_HIDDEN_YELLOW_BLOCK_1_XYZA, GEN_HIDDEN_YELLOW_BLOCK_1_ITEM
#define GEN_HIDDEN_YELLOW_BLOCK_1_FLAG GF_TIK10_HiddenItem_CoinA

// type: Marker:Entity:HiddenYellowBlock
// name: HiddenYellowBlock_2
#define GEN_HIDDEN_YELLOW_BLOCK_2_X 23
#define GEN_HIDDEN_YELLOW_BLOCK_2_Y 70
#define GEN_HIDDEN_YELLOW_BLOCK_2_Z -32
#define GEN_HIDDEN_YELLOW_BLOCK_2_DIR 0
#define GEN_HIDDEN_YELLOW_BLOCK_2_VEC 23,70,-32
#define GEN_HIDDEN_YELLOW_BLOCK_2_XYZA 23, 70, -32, 0
#define GEN_HIDDEN_YELLOW_BLOCK_2_ITEM ITEM_COIN
#define GEN_HIDDEN_YELLOW_BLOCK_2_PARAMS GEN_HIDDEN_YELLOW_BLOCK_2_XYZA, GEN_HIDDEN_YELLOW_BLOCK_2_ITEM
#define GEN_HIDDEN_YELLOW_BLOCK_2_FLAG GF_TIK10_HiddenItem_CoinB

// type: Marker:Entity:HiddenYellowBlock
// name: HiddenYellowBlock_3
#define GEN_HIDDEN_YELLOW_BLOCK_3_X 98
#define GEN_HIDDEN_YELLOW_BLOCK_3_Y 70
#define GEN_HIDDEN_YELLOW_BLOCK_3_Z -32
#define GEN_HIDDEN_YELLOW_BLOCK_3_DIR 0
#define GEN_HIDDEN_YELLOW_BLOCK_3_VEC 98,70,-32
#define GEN_HIDDEN_YELLOW_BLOCK_3_XYZA 98, 70, -32, 0
#define GEN_HIDDEN_YELLOW_BLOCK_3_ITEM ITEM_COIN
#define GEN_HIDDEN_YELLOW_BLOCK_3_PARAMS GEN_HIDDEN_YELLOW_BLOCK_3_XYZA, GEN_HIDDEN_YELLOW_BLOCK_3_ITEM
#define GEN_HIDDEN_YELLOW_BLOCK_3_FLAG GF_TIK10_HiddenItem_CoinC

// type: Marker:Entity:SuperBlock
// name: SuperBlock_1
#define GEN_SUPER_BLOCK_1_X -140
#define GEN_SUPER_BLOCK_1_Y 160
#define GEN_SUPER_BLOCK_1_Z -40
#define GEN_SUPER_BLOCK_1_DIR 0
#define GEN_SUPER_BLOCK_1_VEC -140,160,-40
#define GEN_SUPER_BLOCK_1_XYZA -140, 160, -40, 0
#define GEN_SUPER_BLOCK_1_PARAMS GEN_SUPER_BLOCK_1_XYZA
#define GEN_SUPER_BLOCK_1_VAR MV_SuperBlock
#define GEN_SUPER_BLOCK_1_FLAG GF_TIK10_SuperBlock

// type: Marker:BlockGrid
// name: PushBlocks_1
#define GEN_PUSH_BLOCKS_1_X -64
#define GEN_PUSH_BLOCKS_1_Y -15
#define GEN_PUSH_BLOCKS_1_Z -94
#define GEN_PUSH_BLOCKS_1_DIR 0
#define GEN_PUSH_BLOCKS_1_VEC -64,-15,-94
#define GEN_PUSH_BLOCKS_1_GRID_PARAMS 0, 7, 6, -64, -15, -94, NULL
#define GEN_PUSH_BLOCKS_1_GRID_CONTENT \
    Call(SetPushBlock, 0, 1, 4, PUSH_GRID_BLOCK)

// type: Marker:Volume
// name: DripVolume_1
#define GEN_DRIP_VOLUME_1_X -55
#define GEN_DRIP_VOLUME_1_Y 135
#define GEN_DRIP_VOLUME_1_Z 35
#define GEN_DRIP_VOLUME_1_DIR 0
#define GEN_DRIP_VOLUME_1_VEC -55,135,35
#define GEN_DRIP_VOLUME_1_MIN_X -220
#define GEN_DRIP_VOLUME_1_MIN_Y 20
#define GEN_DRIP_VOLUME_1_MIN_Z 20
#define GEN_DRIP_VOLUME_1_MIN_XZ -220,20
#define GEN_DRIP_VOLUME_1_MIN_VEC -220,20,20
#define GEN_DRIP_VOLUME_1_MAX_X 110
#define GEN_DRIP_VOLUME_1_MAX_Y 250
#define GEN_DRIP_VOLUME_1_MAX_Z 50
#define GEN_DRIP_VOLUME_1_MAX_XZ 110,50
#define GEN_DRIP_VOLUME_1_MAX_VEC 110,250,50

// type: Marker:Volume
// name: DripVolume_2
#define GEN_DRIP_VOLUME_2_X 160
#define GEN_DRIP_VOLUME_2_Y 135
#define GEN_DRIP_VOLUME_2_Z 35
#define GEN_DRIP_VOLUME_2_DIR 0
#define GEN_DRIP_VOLUME_2_VEC 160,135,35
#define GEN_DRIP_VOLUME_2_MIN_X 160
#define GEN_DRIP_VOLUME_2_MIN_Y 20
#define GEN_DRIP_VOLUME_2_MIN_Z 10
#define GEN_DRIP_VOLUME_2_MIN_XZ 160,10
#define GEN_DRIP_VOLUME_2_MIN_VEC 160,20,10
#define GEN_DRIP_VOLUME_2_MAX_X 160
#define GEN_DRIP_VOLUME_2_MAX_Y 250
#define GEN_DRIP_VOLUME_2_MAX_Z 60
#define GEN_DRIP_VOLUME_2_MAX_XZ 160,60
#define GEN_DRIP_VOLUME_2_MAX_VEC 160,250,60

