#include "tst_02.h"
#include "entity.h"

EvtScript N(EVS_MakeEntities) = {
    EVT_MAKE_ENTITY(InertYellowBlock, GEN_INERT_YELLOW_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(InertYellowBlock, GEN_INERT_YELLOW_BLOCK_2_PARAMS)
    EVT_MAKE_ENTITY(InertYellowBlock, GEN_INERT_YELLOW_BLOCK_3_PARAMS)
    EVT_MAKE_ENTITY(InertYellowBlock, GEN_INERT_YELLOW_BLOCK_4_PARAMS)
    EVT_MAKE_ENTITY(InertYellowBlock, GEN_INERT_YELLOW_BLOCK_5_PARAMS)
    EVT_MAKE_ENTITY(GiantChest, GEN_GIANT_CHEST_1_PARAMS)
    EVT_MAKE_ENTITY(Chest, GEN_CHEST_1_PARAMS)
    Return
    End
};
