/* auto-generated, do not edit */
#include "star_rod_macros.h"

// type: MapProperties
#define GEN_MAP_LOCATION LOCATION_PEACHS_CASTLE

// type: EntryList
#define GEN_ENTRY_LIST \
    {  485.0,    0.0,   25.0,  330.0 },

// type: Marker:Entry
// name: Entry_0
#define GEN_ENTRY_0_X 485
#define GEN_ENTRY_0_Y 0
#define GEN_ENTRY_0_Z 25
#define GEN_ENTRY_0_DIR 330
#define GEN_ENTRY_0_VEC 485,0,25

// type: Marker:NPC
// name: NPC_Twink
// anim: ANIM_Twink_Idle
#define GEN_NPC_TWINK_X 0
#define GEN_NPC_TWINK_Y -500
#define GEN_NPC_TWINK_Z 0
#define GEN_NPC_TWINK_DIR 0
#define GEN_NPC_TWINK_VEC 0,-500,0
#define GEN_NPC_TWINK_TERRITORY \
{}

// type: Marker:NPC
// name: NPC_TayceT
// anim: ANIM_TayceT_Idle
#define GEN_NPC_TAYCE_T_X 400
#define GEN_NPC_TAYCE_T_Y 0
#define GEN_NPC_TAYCE_T_Z -70
#define GEN_NPC_TAYCE_T_DIR 90
#define GEN_NPC_TAYCE_T_VEC 400,0,-70
#define GEN_NPC_TAYCE_T_TERRITORY \
{}

// type: Marker:NPC
// name: NPC_Toad
// anim: ANIM_Toad_Red_Idle
#define GEN_NPC_TOAD_X 250
#define GEN_NPC_TOAD_Y 0
#define GEN_NPC_TOAD_Z -110
#define GEN_NPC_TOAD_DIR 270
#define GEN_NPC_TOAD_VEC 250,0,-110
#define GEN_NPC_TOAD_TERRITORY \
{}

// type: Marker:Entity:Item
// name: Item_1
#define GEN_ITEM_1_X 287
#define GEN_ITEM_1_Y 16
#define GEN_ITEM_1_Z -40
#define GEN_ITEM_1_DIR 0
#define GEN_ITEM_1_VEC 287,16,-40
#define GEN_ITEM_1_PARAMS GEN_ITEM_1_ITEM, GEN_ITEM_1_VEC, GEN_ITEM_1_SPAWN, GEN_ITEM_1_FLAG
#define GEN_ITEM_1_ITEM ITEM_CAKE_BOWL
#define GEN_ITEM_1_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_1_FLAG 0

// type: Marker:Entity:Item
// name: Item_2
#define GEN_ITEM_2_X 230
#define GEN_ITEM_2_Y 16
#define GEN_ITEM_2_Z 0
#define GEN_ITEM_2_DIR 0
#define GEN_ITEM_2_VEC 230,16,0
#define GEN_ITEM_2_PARAMS GEN_ITEM_2_ITEM, GEN_ITEM_2_VEC, GEN_ITEM_2_SPAWN, GEN_ITEM_2_FLAG
#define GEN_ITEM_2_ITEM ITEM_CAKE_PAN
#define GEN_ITEM_2_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_2_FLAG 0

// type: Marker:Entity:Item
// name: Item_3
#define GEN_ITEM_3_X 287
#define GEN_ITEM_3_Y 16
#define GEN_ITEM_3_Z -40
#define GEN_ITEM_3_DIR 0
#define GEN_ITEM_3_VEC 287,16,-40
#define GEN_ITEM_3_PARAMS GEN_ITEM_3_ITEM, GEN_ITEM_3_VEC, GEN_ITEM_3_SPAWN, GEN_ITEM_3_FLAG
#define GEN_ITEM_3_ITEM ITEM_CAKE_BOWL
#define GEN_ITEM_3_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_3_FLAG 0

// type: Marker:Entity:Item
// name: Item_4
#define GEN_ITEM_4_X 230
#define GEN_ITEM_4_Y 16
#define GEN_ITEM_4_Z 0
#define GEN_ITEM_4_DIR 0
#define GEN_ITEM_4_VEC 230,16,0
#define GEN_ITEM_4_PARAMS GEN_ITEM_4_ITEM, GEN_ITEM_4_VEC, GEN_ITEM_4_SPAWN, GEN_ITEM_4_FLAG
#define GEN_ITEM_4_ITEM ITEM_CAKE_PAN
#define GEN_ITEM_4_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_4_FLAG 0

// type: Marker:Entity:Item
// name: Item_5
#define GEN_ITEM_5_X 287
#define GEN_ITEM_5_Y 16
#define GEN_ITEM_5_Z -40
#define GEN_ITEM_5_DIR 0
#define GEN_ITEM_5_VEC 287,16,-40
#define GEN_ITEM_5_PARAMS GEN_ITEM_5_ITEM, GEN_ITEM_5_VEC, GEN_ITEM_5_SPAWN, GEN_ITEM_5_FLAG
#define GEN_ITEM_5_ITEM ITEM_CAKE_MIXED
#define GEN_ITEM_5_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_5_FLAG 0

// type: Marker:Entity:Item
// name: Item_6
#define GEN_ITEM_6_X 230
#define GEN_ITEM_6_Y 16
#define GEN_ITEM_6_Z 0
#define GEN_ITEM_6_DIR 0
#define GEN_ITEM_6_VEC 230,16,0
#define GEN_ITEM_6_PARAMS GEN_ITEM_6_ITEM, GEN_ITEM_6_VEC, GEN_ITEM_6_SPAWN, GEN_ITEM_6_FLAG
#define GEN_ITEM_6_ITEM ITEM_CAKE_PAN
#define GEN_ITEM_6_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_6_FLAG 0

// type: Marker:Entity:Item
// name: Item_7
#define GEN_ITEM_7_X 287
#define GEN_ITEM_7_Y 16
#define GEN_ITEM_7_Z -40
#define GEN_ITEM_7_DIR 0
#define GEN_ITEM_7_VEC 287,16,-40
#define GEN_ITEM_7_PARAMS GEN_ITEM_7_ITEM, GEN_ITEM_7_VEC, GEN_ITEM_7_SPAWN, GEN_ITEM_7_FLAG
#define GEN_ITEM_7_ITEM ITEM_CAKE_MIXED
#define GEN_ITEM_7_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_7_FLAG 0

// type: Marker:Entity:Item
// name: Item_8
#define GEN_ITEM_8_X 230
#define GEN_ITEM_8_Y 16
#define GEN_ITEM_8_Z 0
#define GEN_ITEM_8_DIR 0
#define GEN_ITEM_8_VEC 230,16,0
#define GEN_ITEM_8_PARAMS GEN_ITEM_8_ITEM, GEN_ITEM_8_VEC, GEN_ITEM_8_SPAWN, GEN_ITEM_8_FLAG
#define GEN_ITEM_8_ITEM ITEM_CAKE_PAN
#define GEN_ITEM_8_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_8_FLAG 0

// type: Marker:Entity:Item
// name: Item_9
#define GEN_ITEM_9_X 287
#define GEN_ITEM_9_Y 16
#define GEN_ITEM_9_Z -40
#define GEN_ITEM_9_DIR 0
#define GEN_ITEM_9_VEC 287,16,-40
#define GEN_ITEM_9_PARAMS GEN_ITEM_9_ITEM, GEN_ITEM_9_VEC, GEN_ITEM_9_SPAWN, GEN_ITEM_9_FLAG
#define GEN_ITEM_9_ITEM ITEM_CAKE_MIXED
#define GEN_ITEM_9_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_9_FLAG 0

// type: Marker:Entity:Item
// name: Item_10
#define GEN_ITEM_10_X 230
#define GEN_ITEM_10_Y 16
#define GEN_ITEM_10_Z 0
#define GEN_ITEM_10_DIR 0
#define GEN_ITEM_10_VEC 230,16,0
#define GEN_ITEM_10_PARAMS GEN_ITEM_10_ITEM, GEN_ITEM_10_VEC, GEN_ITEM_10_SPAWN, GEN_ITEM_10_FLAG
#define GEN_ITEM_10_ITEM ITEM_CAKE_PAN
#define GEN_ITEM_10_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_10_FLAG 0

// type: Marker:Entity:Item
// name: Item_11
#define GEN_ITEM_11_X 287
#define GEN_ITEM_11_Y 20
#define GEN_ITEM_11_Z -30
#define GEN_ITEM_11_DIR 0
#define GEN_ITEM_11_VEC 287,20,-30
#define GEN_ITEM_11_PARAMS GEN_ITEM_11_ITEM, GEN_ITEM_11_VEC, GEN_ITEM_11_SPAWN, GEN_ITEM_11_FLAG
#define GEN_ITEM_11_ITEM ITEM_CAKE_BARE
#define GEN_ITEM_11_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_11_FLAG 0

// type: Marker:Entity:Item
// name: Item_12
#define GEN_ITEM_12_X 230
#define GEN_ITEM_12_Y 16
#define GEN_ITEM_12_Z 0
#define GEN_ITEM_12_DIR 0
#define GEN_ITEM_12_VEC 230,16,0
#define GEN_ITEM_12_PARAMS GEN_ITEM_12_ITEM, GEN_ITEM_12_VEC, GEN_ITEM_12_SPAWN, GEN_ITEM_12_FLAG
#define GEN_ITEM_12_ITEM ITEM_CAKE_BOWL
#define GEN_ITEM_12_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_12_FLAG 0

// type: Marker:Entity:Item
// name: Item_13
#define GEN_ITEM_13_X 287
#define GEN_ITEM_13_Y 16
#define GEN_ITEM_13_Z -40
#define GEN_ITEM_13_DIR 0
#define GEN_ITEM_13_VEC 287,16,-40
#define GEN_ITEM_13_PARAMS GEN_ITEM_13_ITEM, GEN_ITEM_13_VEC, GEN_ITEM_13_SPAWN, GEN_ITEM_13_FLAG
#define GEN_ITEM_13_ITEM ITEM_CAKE_MIXED
#define GEN_ITEM_13_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_13_FLAG 0

// type: Marker:Entity:Item
// name: Item_14
#define GEN_ITEM_14_X 287
#define GEN_ITEM_14_Y 20
#define GEN_ITEM_14_Z -30
#define GEN_ITEM_14_DIR 0
#define GEN_ITEM_14_VEC 287,20,-30
#define GEN_ITEM_14_PARAMS GEN_ITEM_14_ITEM, GEN_ITEM_14_VEC, GEN_ITEM_14_SPAWN, GEN_ITEM_14_FLAG
#define GEN_ITEM_14_ITEM ITEM_CAKE_WITH_BERRIES
#define GEN_ITEM_14_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_14_FLAG 0

// type: Marker:Entity:Item
// name: Item_15
#define GEN_ITEM_15_X 287
#define GEN_ITEM_15_Y 20
#define GEN_ITEM_15_Z -30
#define GEN_ITEM_15_DIR 0
#define GEN_ITEM_15_VEC 287,20,-30
#define GEN_ITEM_15_PARAMS GEN_ITEM_15_ITEM, GEN_ITEM_15_VEC, GEN_ITEM_15_SPAWN, GEN_ITEM_15_FLAG
#define GEN_ITEM_15_ITEM ITEM_CAKE_DONE
#define GEN_ITEM_15_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_15_FLAG 0

// type: Marker:Entity:Item
// name: Item_16
#define GEN_ITEM_16_X 287
#define GEN_ITEM_16_Y 20
#define GEN_ITEM_16_Z -30
#define GEN_ITEM_16_DIR 0
#define GEN_ITEM_16_VEC 287,20,-30
#define GEN_ITEM_16_PARAMS GEN_ITEM_16_ITEM, GEN_ITEM_16_VEC, GEN_ITEM_16_SPAWN, GEN_ITEM_16_FLAG
#define GEN_ITEM_16_ITEM ITEM_CAKE_WITH_ICING
#define GEN_ITEM_16_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_16_FLAG 0

// type: Marker:Entity:Item
// name: Item_17
#define GEN_ITEM_17_X 287
#define GEN_ITEM_17_Y 16
#define GEN_ITEM_17_Z -40
#define GEN_ITEM_17_DIR 0
#define GEN_ITEM_17_VEC 287,16,-40
#define GEN_ITEM_17_PARAMS GEN_ITEM_17_ITEM, GEN_ITEM_17_VEC, GEN_ITEM_17_SPAWN, GEN_ITEM_17_FLAG
#define GEN_ITEM_17_ITEM ITEM_CAKE_MIXED
#define GEN_ITEM_17_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_17_FLAG 0

// type: Marker:Entity:Item
// name: Item_18
#define GEN_ITEM_18_X 230
#define GEN_ITEM_18_Y 16
#define GEN_ITEM_18_Z 0
#define GEN_ITEM_18_DIR 0
#define GEN_ITEM_18_VEC 230,16,0
#define GEN_ITEM_18_PARAMS GEN_ITEM_18_ITEM, GEN_ITEM_18_VEC, GEN_ITEM_18_SPAWN, GEN_ITEM_18_FLAG
#define GEN_ITEM_18_ITEM ITEM_CAKE_BATTER
#define GEN_ITEM_18_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_18_FLAG 0

// type: Marker:Entity:Item
// name: Item_19
#define GEN_ITEM_19_X 250
#define GEN_ITEM_19_Y 16
#define GEN_ITEM_19_Z 0
#define GEN_ITEM_19_DIR 0
#define GEN_ITEM_19_VEC 250,16,0
#define GEN_ITEM_19_PARAMS GEN_ITEM_19_ITEM, GEN_ITEM_19_VEC, GEN_ITEM_19_SPAWN, GEN_ITEM_19_FLAG
#define GEN_ITEM_19_ITEM ITEM_CAKE_BOWL
#define GEN_ITEM_19_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_19_FLAG 0

// type: Marker:Entity:Item
// name: Item_20
#define GEN_ITEM_20_X 100
#define GEN_ITEM_20_Y 5
#define GEN_ITEM_20_Z -135
#define GEN_ITEM_20_DIR 0
#define GEN_ITEM_20_VEC 100,5,-135
#define GEN_ITEM_20_PARAMS GEN_ITEM_20_ITEM, GEN_ITEM_20_VEC, GEN_ITEM_20_SPAWN, GEN_ITEM_20_FLAG
#define GEN_ITEM_20_ITEM ITEM_CAKE_BATTER
#define GEN_ITEM_20_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_20_FLAG 0

// type: Marker:Entity:Item
// name: Item_21
#define GEN_ITEM_21_X 287
#define GEN_ITEM_21_Y 16
#define GEN_ITEM_21_Z -40
#define GEN_ITEM_21_DIR 0
#define GEN_ITEM_21_VEC 287,16,-40
#define GEN_ITEM_21_PARAMS GEN_ITEM_21_ITEM, GEN_ITEM_21_VEC, GEN_ITEM_21_SPAWN, GEN_ITEM_21_FLAG
#define GEN_ITEM_21_ITEM ITEM_CAKE_BATTER
#define GEN_ITEM_21_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_21_FLAG 0

// type: Marker:Entity:Item
// name: Item_22
#define GEN_ITEM_22_X 287
#define GEN_ITEM_22_Y 20
#define GEN_ITEM_22_Z -30
#define GEN_ITEM_22_DIR 0
#define GEN_ITEM_22_VEC 287,20,-30
#define GEN_ITEM_22_PARAMS GEN_ITEM_22_ITEM, GEN_ITEM_22_VEC, GEN_ITEM_22_SPAWN, GEN_ITEM_22_FLAG
#define GEN_ITEM_22_ITEM ITEM_CAKE_BARE
#define GEN_ITEM_22_SPAWN ITEM_SPAWN_MODE_DECORATION
#define GEN_ITEM_22_FLAG 0

// type: Marker:Path
// name: Path_1
#define GEN_PATH_1_X 630
#define GEN_PATH_1_Y 100
#define GEN_PATH_1_Z -124
#define GEN_PATH_1_DIR 0
#define GEN_PATH_1_VEC 630,100,-124
#define GEN_PATH_1_PATH \
    {  440,   25,  -30 }, \
    {  480,   60,  -60 }, \
    {  550,   50,  -90 }, \
    {  590,   40, -110 }, \
    {  630,  100, -124 },

