#include "tst_03.h"
#include "entity.h"

EvtScript N(EVS_MakeEntities) = {
    EVT_MAKE_ENTITY(RedBlock, GEN_RED_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(HiddenRedBlock, GEN_HIDDEN_RED_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(InertYellowBlock, GEN_INERT_YELLOW_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(BrickBlock, GEN_BRICK_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(MulticoinBlock, GEN_MULTICOIN_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(YellowBlock, GEN_YELLOW_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(TriggerBlock, GEN_TRIGGER_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(HiddenYellowBlock, GEN_HIDDEN_YELLOW_BLOCK_1_PARAMS)
    Call(MakeEntity, Ref(Entity_SuperBlock), 300, 60, 160, 0, MAKE_ENTITY_END)
    EVT_MAKE_ENTITY(HeartBlock, GEN_HEART_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(SavePoint, GEN_SAVE_POINT_1_PARAMS)
    EVT_MAKE_ENTITY(PowBlock, GEN_POW_BLOCK_1_PARAMS)
    EVT_MAKE_ENTITY(Hammer1BlockTiny, GEN_HAMMER1_BLOCK_TINY_1_PARAMS)
    EVT_MAKE_ENTITY(Hammer1BlockTiny, GEN_HAMMER1_BLOCK_TINY_2_PARAMS)
    EVT_MAKE_ENTITY(Hammer2BlockTiny, GEN_HAMMER2_BLOCK_TINY_1_PARAMS)
    EVT_MAKE_ENTITY(Hammer3BlockTiny, GEN_HAMMER3_BLOCK_TINY_1_PARAMS)
    EVT_MAKE_ENTITY(PowBlock, GEN_POW_BLOCK_2_PARAMS)
    EVT_MAKE_ENTITY(BoardedFloor, GEN_BOARDED_FLOOR_1_PARAMS)
    EVT_MAKE_ENTITY(WoodenCrate, GEN_WOODEN_CRATE_1_PARAMS)
    EVT_MAKE_ENTITY(WoodenCrate, GEN_WOODEN_CRATE_2_PARAMS)
    EVT_MAKE_ENTITY(WoodenCrate, GEN_WOODEN_CRATE_3_PARAMS)
    Return
    End
};
