/* auto-generated, do not edit */
#include "star_rod_macros.h"

// type: MapProperties
#define GEN_MAP_LOCATION LOCATION_TOAD_TOWN_TUNNELS

// type: EntryList
#define GEN_ENTRY_LIST \
    { -325.0,  -20.0,    0.0,   90.0 }, \
    {  325.0,  -20.0,    0.0,  270.0 }, \
    {  270.0, -105.0,   93.0,  180.0 },

// type: TexPanner
#define GEN_TEX_PANNER_0 \
    TEX_PAN_PARAMS_ID(TEX_PANNER_0) \
    TEX_PAN_PARAMS_STEP(     0,  -200,  -100,  -500) \
    TEX_PAN_PARAMS_FREQ(     0,     1,     1,     1) \
    TEX_PAN_PARAMS_INIT(     0,     0,     0,     0)

// type: Marker:Entry
// name: Entry_0
#define GEN_ENTRY_0_X -325
#define GEN_ENTRY_0_Y -20
#define GEN_ENTRY_0_Z 0
#define GEN_ENTRY_0_DIR 90
#define GEN_ENTRY_0_VEC -325,-20,0

// type: Marker:Entry
// name: Entry_1
#define GEN_ENTRY_1_X 325
#define GEN_ENTRY_1_Y -20
#define GEN_ENTRY_1_Z 0
#define GEN_ENTRY_1_DIR 270
#define GEN_ENTRY_1_VEC 325,-20,0

// type: Marker:Entry
// name: Entry_2
#define GEN_ENTRY_2_X 270
#define GEN_ENTRY_2_Y -105
#define GEN_ENTRY_2_Z 93
#define GEN_ENTRY_2_DIR 180
#define GEN_ENTRY_2_VEC 270,-105,93

// type: Marker:Entity:YellowBlock
// name: YellowBlock_1
#define GEN_YELLOW_BLOCK_1_X -157
#define GEN_YELLOW_BLOCK_1_Y -45
#define GEN_YELLOW_BLOCK_1_Z 0
#define GEN_YELLOW_BLOCK_1_DIR 0
#define GEN_YELLOW_BLOCK_1_VEC -157,-45,0
#define GEN_YELLOW_BLOCK_1_XYZA -157, -45, 0, 0
#define GEN_YELLOW_BLOCK_1_ITEM ITEM_COIN
#define GEN_YELLOW_BLOCK_1_PARAMS GEN_YELLOW_BLOCK_1_XYZA, GEN_YELLOW_BLOCK_1_ITEM
#define GEN_YELLOW_BLOCK_1_FLAG GF_TIK21_ItemBlock_Coin

// type: Marker:Entity:HiddenYellowBlock
// name: HiddenYellowBlock_1
#define GEN_HIDDEN_YELLOW_BLOCK_1_X -82
#define GEN_HIDDEN_YELLOW_BLOCK_1_Y -45
#define GEN_HIDDEN_YELLOW_BLOCK_1_Z 0
#define GEN_HIDDEN_YELLOW_BLOCK_1_DIR 0
#define GEN_HIDDEN_YELLOW_BLOCK_1_VEC -82,-45,0
#define GEN_HIDDEN_YELLOW_BLOCK_1_XYZA -82, -45, 0, 0
#define GEN_HIDDEN_YELLOW_BLOCK_1_ITEM ITEM_COIN
#define GEN_HIDDEN_YELLOW_BLOCK_1_PARAMS GEN_HIDDEN_YELLOW_BLOCK_1_XYZA, GEN_HIDDEN_YELLOW_BLOCK_1_ITEM
#define GEN_HIDDEN_YELLOW_BLOCK_1_FLAG GF_TIK21_HiddenItem_CoinA

// type: Marker:Entity:HiddenYellowBlock
// name: HiddenYellowBlock_2
#define GEN_HIDDEN_YELLOW_BLOCK_2_X -7
#define GEN_HIDDEN_YELLOW_BLOCK_2_Y -45
#define GEN_HIDDEN_YELLOW_BLOCK_2_Z 0
#define GEN_HIDDEN_YELLOW_BLOCK_2_DIR 0
#define GEN_HIDDEN_YELLOW_BLOCK_2_VEC -7,-45,0
#define GEN_HIDDEN_YELLOW_BLOCK_2_XYZA -7, -45, 0, 0
#define GEN_HIDDEN_YELLOW_BLOCK_2_ITEM ITEM_COIN
#define GEN_HIDDEN_YELLOW_BLOCK_2_PARAMS GEN_HIDDEN_YELLOW_BLOCK_2_XYZA, GEN_HIDDEN_YELLOW_BLOCK_2_ITEM
#define GEN_HIDDEN_YELLOW_BLOCK_2_FLAG GF_TIK21_HiddenItem_CoinB

// type: Marker:Entity:HiddenYellowBlock
// name: HiddenYellowBlock_3
#define GEN_HIDDEN_YELLOW_BLOCK_3_X 68
#define GEN_HIDDEN_YELLOW_BLOCK_3_Y -45
#define GEN_HIDDEN_YELLOW_BLOCK_3_Z 0
#define GEN_HIDDEN_YELLOW_BLOCK_3_DIR 0
#define GEN_HIDDEN_YELLOW_BLOCK_3_VEC 68,-45,0
#define GEN_HIDDEN_YELLOW_BLOCK_3_XYZA 68, -45, 0, 0
#define GEN_HIDDEN_YELLOW_BLOCK_3_ITEM ITEM_COIN
#define GEN_HIDDEN_YELLOW_BLOCK_3_PARAMS GEN_HIDDEN_YELLOW_BLOCK_3_XYZA, GEN_HIDDEN_YELLOW_BLOCK_3_ITEM
#define GEN_HIDDEN_YELLOW_BLOCK_3_FLAG GF_TIK21_HiddenItem_CoinC

// type: Marker:Entity:HiddenYellowBlock
// name: HiddenYellowBlock_4
#define GEN_HIDDEN_YELLOW_BLOCK_4_X 142
#define GEN_HIDDEN_YELLOW_BLOCK_4_Y -45
#define GEN_HIDDEN_YELLOW_BLOCK_4_Z 0
#define GEN_HIDDEN_YELLOW_BLOCK_4_DIR 0
#define GEN_HIDDEN_YELLOW_BLOCK_4_VEC 142,-45,0
#define GEN_HIDDEN_YELLOW_BLOCK_4_XYZA 142, -45, 0, 0
#define GEN_HIDDEN_YELLOW_BLOCK_4_ITEM ITEM_COIN
#define GEN_HIDDEN_YELLOW_BLOCK_4_PARAMS GEN_HIDDEN_YELLOW_BLOCK_4_XYZA, GEN_HIDDEN_YELLOW_BLOCK_4_ITEM
#define GEN_HIDDEN_YELLOW_BLOCK_4_FLAG GF_TIK21_HiddenItem_CoinD

// type: Marker:Volume
// name: DripVolume_1
#define GEN_DRIP_VOLUME_1_X -130
#define GEN_DRIP_VOLUME_1_Y 90
#define GEN_DRIP_VOLUME_1_Z 13
#define GEN_DRIP_VOLUME_1_DIR 0
#define GEN_DRIP_VOLUME_1_VEC -130,90,13
#define GEN_DRIP_VOLUME_1_MIN_X -320
#define GEN_DRIP_VOLUME_1_MIN_Y -20
#define GEN_DRIP_VOLUME_1_MIN_Z -19
#define GEN_DRIP_VOLUME_1_MIN_XZ -320,-19
#define GEN_DRIP_VOLUME_1_MIN_VEC -320,-20,-19
#define GEN_DRIP_VOLUME_1_MAX_X 60
#define GEN_DRIP_VOLUME_1_MAX_Y 200
#define GEN_DRIP_VOLUME_1_MAX_Z 46
#define GEN_DRIP_VOLUME_1_MAX_XZ 60,46
#define GEN_DRIP_VOLUME_1_MAX_VEC 60,200,46

// type: Marker:Volume
// name: DripVolume_2
#define GEN_DRIP_VOLUME_2_X 139
#define GEN_DRIP_VOLUME_2_Y 90
#define GEN_DRIP_VOLUME_2_Z 67
#define GEN_DRIP_VOLUME_2_DIR 0
#define GEN_DRIP_VOLUME_2_VEC 139,90,67
#define GEN_DRIP_VOLUME_2_MIN_X 45
#define GEN_DRIP_VOLUME_2_MIN_Y -20
#define GEN_DRIP_VOLUME_2_MIN_Z -100
#define GEN_DRIP_VOLUME_2_MIN_XZ 45,-100
#define GEN_DRIP_VOLUME_2_MIN_VEC 45,-20,-100
#define GEN_DRIP_VOLUME_2_MAX_X 233
#define GEN_DRIP_VOLUME_2_MAX_Y 200
#define GEN_DRIP_VOLUME_2_MAX_Z 235
#define GEN_DRIP_VOLUME_2_MAX_XZ 233,235
#define GEN_DRIP_VOLUME_2_MAX_VEC 233,200,235

